spring.application.name=spring-boot-demo

spring.datasource.url=jdbc:mysql://localhost:3306/java_db
spring.datasource.username=root
spring.datasource.password=Password1234

# Hibernate Properties
# 'update' will create/modify tables based on your Java entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect